/* Automatically generated by './build/bin/build-entry.js' */

import Input from '../packages/input/index.js';

const components = [
  Input
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$ELEMENT = {
    // 全局统一设置元素默认的size和默认zIndex
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
  Input
};
